spring:
  application:
    name: catalog-service #설정 서버에서 설정을 필터링하는 데 사용하는 애플리케이션 이름
  config:
    import: "optional:configserver:"  #가능하면 컨피그 서버에서 설정데이터를 가져온다.
  cloud:
    config:
      uri: http://localhost:8888 #설정 서버의 URL